name: Handle Incoming Zoho Data

on:
  repository_dispatch:
    types: [tech_vector_export]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Read Payload Data
        run: |
          echo "Received data from Zoho!"
          echo "Payload content: '${{ toJson(github.event.client_payload) }}'"
